### ISSUE TITLE
double free or corruption (fasttop): 0x0000000006cfbc20 In Linux

### ISSUE THREAD

**Issue by cauchyturing** [quasars84/geekminer#2]
Hi, I compiled the ccminer in linux, all is fine with CUDA 8.0. but when running it fails. The error message 

`*** nevermore/0.1 for nVidia GPUs *** 
    Built with the nVidia CUDA Toolkit 8.0 64-bits

  Originally based on Christian Buchner and Christian H. project
  Include some kernels from alexis78, djm34, djEzo, tsiv and krnlx.

Dev donation set to 1.0%

*** Error in `./ccminer': double free or corruption (fasttop): 0x00000000089aa880 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fa17f3497e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fa17f35237a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fa17f35653c]
./ccminer[0x41dfcc]
./ccminer[0x4066ef]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0)[0x7fa17f2f2830]
./ccminer[0x40f2f9]
======= Memory map: ========
00400000-038b9000 r-xp 00000000 08:12 6647822                            /home/stephen/Downloads/geekminer/ccminer
03ab9000-03aba000 r--p 034b9000 08:12 6647822                            /home/stephen/Downloads/geekminer/ccminer
03aba000-03abe000 rw-p 034ba000 08:12 6647822                            /home/stephen/Downloads/geekminer/ccminer
03abe000-06b76000 rw-p 00000000 00:00 0 
08952000-089b2000 rw-p 00000000 00:00 0                                  [heap]
200000000-300200000 ---p 00000000 00:00 0 
10000000000-10100000000 ---p 00000000 00:00 0 
7fa16c000000-7fa16c021000 rw-p 00000000 00:00 0 
7fa16c021000-7fa170000000 ---p 00000000 00:00 0 
7fa173dcb000-7fa173dcc000 ---p 00000000 00:00 0 
7fa173dcc000-7fa1745cc000 rw-p 00000000 00:00 0 
7fa1745cc000-7fa17a5cc000 ---p 00000000 00:00 0 
7fa17a5cc000-7fa17a5d5000 r-xp 00000000 08:12 8924910                    /lib/x86_64-linux-gnu/libcrypt-2.23.so
7fa17a5d5000-7fa17a7d4000 ---p 00009000 08:12 8924910                    /lib/x86_64-linux-gnu/libcrypt-2.23.so
7fa17a7d4000-7fa17a7d5000 r--p 00008000 08:12 8924910                    /lib/x86_64-linux-gnu/libcrypt-2.23.so
7fa17a7d5000-7fa17a7d6000 rw-p 00009000 08:12 8924910                    /lib/x86_64-linux-gnu/libcrypt-2.23.so
7fa17a7d6000-7fa17a804000 rw-p 00000000 00:00 0 
7fa17a804000-7fa17a8d3000 r-xp 00000000 08:12 9445816                    /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7fa17a8d3000-7fa17aad3000 ---p 000cf000 08:12 9445816                    /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7fa17aad3000-7fa17aad6000 r--p 000cf000 08:12 9445816                    /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7fa17aad6000-7fa17aad8000 rw-p 000d2000 08:12 9445816                    /usr/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
7fa17aad8000-7fa17aad9000 rw-p 00000000 00:00 0 
7fa17aad9000-7fa17ab20000 r-xp 00000000 08:12 9440670                    /usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0
7fa17ab20000-7fa17ad1f000 ---p 00047000 08:12 9440670                    /usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0
7fa17ad1f000-7fa17ad21000 r--p 00046000 08:12 9440670                    /usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0
7fa17ad21000-7fa17ad23000 rw-p 00048000 08:12 9440670                    /usr/lib/x86_64-linux-gnu/libhx509.so.5.0.0
7fa17ad23000-7fa17ad24000 rw-p 00000000 00:00 0 
7fa17ad24000-7fa17ad32000 r-xp 00000000 08:12 9440666                    /usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0
7fa17ad32000-7fa17af31000 ---p 0000e000 08:12 9440666                    /usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0
7fa17af31000-7fa17af32000 r--p 0000d000 08:12 9440666                    /usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0
7fa17af32000-7fa17af33000 rw-p 0000e000 08:12 9440666                    /usr/lib/x86_64-linux-gnu/libheimbase.so.1.0.0
7fa17af33000-7fa17af5a000 r-xp 00000000 08:12 9440668                    /usr/lib/x86_64-linux-gnu/libwind.so.0.0.0
7fa17af5a000-7fa17b15a000 ---p 00027000 08:12 9440668                    /usr/lib/x86_64-linux-gnu/libwind.so.0.0.0
7fa17b15a000-7fa17b15b000 r--p 00027000 08:12 9440668                    /usr/lib/x86_64-linux-gnu/libwind.so.0.0.0
7fa17b15b000-7fa17b15c000 rw-p 00028000 08:12 9440668                    /usr/lib/x86_64-linux-gnu/libwind.so.0.0.0
7fa17b15c000-7fa17b163000 r-xp 00000000 08:12 9437321                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7fa17b163000-7fa17b362000 ---p 00007000 08:12 9437321                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7fa17b362000-7fa17b363000 r--p 00006000 08:12 9437321                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7fa17b363000-7fa17b364000 rw-p 00007000 08:12 9437321                    /usr/lib/x86_64-linux-gnu/libffi.so.6.0.4
7fa17b364000-7fa17b379000 r-xp 00000000 08:12 9440659                    /usr/lib/x86_64-linux-gnu/libroken.so.18.1.0
7fa17b379000-7fa17b578000 ---p 00015000 08:12 9440659                    /usr/lib/x86_64-linux-gnu/libroken.so.18.1.0
7fa17b578000-7fa17b579000 r--p 00014000 08:12 9440659                    /usr/lib/x86_64-linux-gnu/libroken.so.18.1.0
7fa17b579000-7fa17b57a000 rw-p 00015000 08:12 9440659                    /usr/lib/x86_64-linux-gnu/libroken.so.18.1.0
7fa17b57a000-7fa17b5aa000 r-xp 00000000 08:12 9440664                    /usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0
7fa17b5aa000-7fa17b7aa000 ---p 00030000 08:12 9440664                    /usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0
7fa17b7aa000-7fa17b7ab000 r--p 00030000 08:12 9440664                    /usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0
7fa17b7ab000-7fa17b7ac000 rw-p 00031000 08:12 9440664                    /usr/lib/x86_64-linux-gnu/libhcrypto.so.4.1.0
7fa17b7ac000-7fa17b7ad000 rw-p 00000000 00:00 0 
7fa17b7ad000-7fa17b84c000 r-xp 00000000 08:12 9440660                    /usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0
7fa17b84c000-7fa17ba4b000 ---p 0009f000 08:12 9440660                    /usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0
7fa17ba4b000-7fa17ba4c000 r--p 0009e000 08:12 9440660                    /usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0
7fa17ba4c000-7fa17ba4f000 rw-p 0009f000 08:12 9440660                    /usr/lib/x86_64-linux-gnu/libasn1.so.8.0.0
7fa17ba4f000-7fa17bad3000 r-xp 00000000 08:12 9440672                    /usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0
7fa17bad3000-7fa17bcd2000 ---p 00084000 08:12 9440672                    /usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0
7fa17bcd2000-7fa17bcd5000 r--p 00083000 08:12 9440672                    /usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0
7fa17bcd5000-7fa17bcd8000 rw-p 00086000 08:12 9440672                    /usr/lib/x86_64-linux-gnu/libkrb5.so.26.0.0
7fa17bcd8000-7fa17bcd9000 rw-p 00000000 00:00 0 
7fa17bcd9000-7fa17bce1000 r-xp 00000000 08:12 9440674                    /usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0
7fa17bce1000-7fa17bee0000 ---p 00008000 08:12 9440674                    /usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0
7fa17bee0000-7fa17bee1000 r--p 00007000 08:12 9440674                    /usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0
7fa17bee1000-7fa17bee2000 rw-p 00008000 08:12 9440674                    /usr/lib/x86_64-linux-gnu/libheimntlm.so.0.1.0
7fa17bee2000-7fa17bee5000 r-xp 00000000 08:12 8917239                    /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7fa17bee5000-7fa17c0e4000 ---p 00003000 08:12 8917239                    /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7fa17c0e4000-7fa17c0e5000 r--p 00002000 08:12 8917239                    /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7fa17c0e5000-7fa17c0e6000 rw-p 00003000 08:12 8917239                    /lib/x86_64-linux-gnu/libkeyutils.so.1.5
7fa17c0e6000-7fa17c0f7000 r-xp 00000000 08:12 9438273                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7fa17c0f7000-7fa17c2f7000 ---p 00011000 08:12 9438273                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7fa17c2f7000-7fa17c2f8000 r--p 00011000 08:12 9438273                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7fa17c2f8000-7fa17c2f9000 rw-p 00012000 08:12 9438273                    /usr/lib/x86_64-linux-gnu/libtasn1.so.6.5.1
7fa17c2f9000-7fa17c352000 r-xp 00000000 08:12 9450910                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7fa17c352000-7fa17c551000 ---p 00059000 08:12 9450910                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7fa17c551000-7fa17c55b000 r--p 00058000 08:12 9450910                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7fa17c55b000-7fa17c55d000 rw-p 00062000 08:12 9450910                    /usr/lib/x86_64-linux-gnu/libp11-kit.so.0.1.0
7fa17c55d000-7fa17c59a000 r-xp 00000000 08:12 9440676                    /usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
7fa17c59a000-7fa17c79a000 ---p 0003d000 08:12 9440676                    /usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
7fa17c79a000-7fa17c79b000 r--p 0003d000 08:12 9440676                    /usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
7fa17c79b000-7fa17c79d000 rw-p 0003e000 08:12 9440676                    /usr/lib/x86_64-linux-gnu/libgssapi.so.3.0.0
7fa17c79d000-7fa17c79e000 rw-p 00000000 00:00 0 
7fa17c79e000-7fa17c7b7000 r-xp 00000000 08:12 9440679                    /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7fa17c7b7000-7fa17c9b7000 ---p 00019000 08:12 9440679                    /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7fa17c9b7000-7fa17c9b8000 r--p 00019000 08:12 9440679                    /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7fa17c9b8000-7fa17c9b9000 rw-p 0001a000 08:12 9440679                    /usr/lib/x86_64-linux-gnu/libsasl2.so.2.0.25
7fa17c9b9000-7fa17c9d0000 r-xp 00000000 08:12 8924895                    /lib/x86_64-linux-gnu/libresolv-2.23.so
7fa17c9d0000-7fa17cbd0000 ---p 00017000 08:12 8924895                    /lib/x86_64-linux-gnu/libresolv-2.23.so
7fa17cbd0000-7fa17cbd1000 r--p 00017000 08:12 8924895                    /lib/x86_64-linux-gnu/libresolv-2.23.so
7fa17cbd1000-7fa17cbd2000 rw-p 00018000 08:12 8924895                    /lib/x86_64-linux-gnu/libresolv-2.23.so
7fa17cbd2000-7fa17cbd4000 rw-p 00000000 00:00 0 
7fa17cbd4000-7fa17cbde000 r-xp 00000000 08:12 9442833                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7fa17cbde000-7fa17cddd000 ---p 0000a000 08:12 9442833                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7fa17cddd000-7fa17cdde000 r--p 00009000 08:12 9442833                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7fa17cdde000-7fa17cddf000 rw-p 0000a000 08:12 9442833                    /usr/lib/x86_64-linux-gnu/libkrb5support.so.0.1
7fa17cddf000-7fa17cde2000 r-xp 00000000 08:12 8917159                    /lib/x86_64-linux-gnu/libcom_err.so.2.1
7fa17cde2000-7fa17cfe1000 ---p 00003000 08:12 8917159                    /lib/x86_64-linux-gnu/libcom_err.so.2.1
7fa17cfe1000-7fa17cfe2000 r--p 00002000 08:12 8917159                    /lib/x86_64-linux-gnu/libcom_err.so.2.1
7fa17cfe2000-7fa17cfe3000 rw-p 00003000 08:12 8917159                    /lib/x86_64-linux-gnu/libcom_err.so.2.1
7fa17cfe3000-7fa17d00f000 r-xp 00000000 08:12 9442823                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7fa17d00f000-7fa17d20e000 ---p 0002c000 08:12 9442823                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7fa17d20e000-7fa17d210000 r--p 0002b000 08:12 9442823                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7fa17d210000-7fa17d211000 rw-p 0002d000 08:12 9442823                    /usr/lib/x86_64-linux-gnu/libk5crypto.so.3.1
7fa17d211000-7fa17d212000 rw-p 00000000 00:00 0 
7fa17d212000-7fa17d2d5000 r-xp 00000000 08:12 9442835                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7fa17d2d5000-7fa17d4d5000 ---p 000c3000 08:12 9442835                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7fa17d4d5000-7fa17d4e2000 r--p 000c3000 08:12 9442835                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7fa17d4e2000-7fa17d4e4000 rw-p 000d0000 08:12 9442835                    /usr/lib/x86_64-linux-gnu/libkrb5.so.3.3
7fa17d4e4000-7fa17d563000 r-xp 00000000 08:12 9437918                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7fa17d563000-7fa17d762000 ---p 0007f000 08:12 9437918                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7fa17d762000-7fa17d763000 r--p 0007e000 08:12 9437918                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7fa17d763000-7fa17d764000 rw-p 0007f000 08:12 9437918                    /usr/lib/x86_64-linux-gnu/libgmp.so.10.3.0
7fa17d764000-7fa17d798000 r-xp 00000000 08:12 9440176                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7fa17d798000-7fa17d997000 ---p 00034000 08:12 9440176                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7fa17d997000-7fa17d999000 r--p 00033000 08:12 9440176                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7fa17d999000-7fa17d99a000 rw-p 00035000 08:12 9440176                    /usr/lib/x86_64-linux-gnu/libnettle.so.6.2
7fa17d99a000-7fa17d9cc000 r-xp 00000000 08:12 9445612                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7fa17d9cc000-7fa17dbcb000 ---p 00032000 08:12 9445612                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7fa17dbcb000-7fa17dbcc000 r--p 00031000 08:12 9445612                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7fa17dbcc000-7fa17dbcd000 rw-p 00032000 08:12 9445612                    /usr/lib/x86_64-linux-gnu/libhogweed.so.4.2
7fa17dbcd000-7fa17dcf0000 r-xp 00000000 08:12 9439419                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7fa17dcf0000-7fa17deef000 ---p 00123000 08:12 9439419                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7fa17deef000-7fa17defa000 r--p 00122000 08:12 9439419                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7fa17defa000-7fa17defc000 rw-p 0012d000 08:12 9439419                    /usr/lib/x86_64-linux-gnu/libgnutls.so.30.6.2
7fa17defc000-7fa17defd000 rw-p 00000000 00:00 0 
7fa17defd000-7fa17df3f000 r-xp 00000000 08:12 10359008                   /usr/lib/nvidia-378/libnvidia-fatbinaryloader.so.378.09
7fa17df3f000-7fa17e13e000 ---p 00042000 08:12 10359008                   /usr/lib/nvidia-378/libnvidia-fatbinaryloader.so.378.09
7fa17e13e000-7fa17e149000 rw-p 00041000 08:12 10359008                   /usr/lib/nvidia-378/libnvidia-fatbinaryloader.so.378.09
7fa17e149000-7fa17e14e000 rw-p 00000000 00:00 0 
7fa17e14e000-7fa17e155000 r-xp 00000000 08:12 8924909                    /lib/x86_64-linux-gnu/librt-2.23.so
7fa17e155000-7fa17e354000 ---p 00007000 08:12 8924909                    /lib/x86_64-linux-gnu/librt-2.23.so
7fa17e354000-7fa17e355000 r--p 00006000 08:12 8924909                    /lib/x86_64-linux-gnu/librt-2.23.so
7fa17e355000-7fa17e356000 rw-p 00007000 08:12 8924909                    /lib/x86_64-linux-gnu/librt-2.23.so
7fa17e356000-7fa17e36f000 r-xp 00000000 08:12 8912925                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7fa17e36f000-7fa17e56e000 ---p 00019000 08:12 8912925                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7fa17e56e000-7fa17e56f000 r--p 00018000 08:12 8912925                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7fa17e56f000-7fa17e570000 rw-p 00019000 08:12 8912925                    /lib/x86_64-linux-gnu/libz.so.1.2.8
7fa17e570000-7fa17e5bd000 r-xp 00000000 08:12 9437852                    /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.5
7fa17e5bd000-7fa17e7bc000 ---p 0004d000 08:12 9437852                    /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.5
7fa17e7bc000-7fa17e7be000 r--p 0004c000 08:12 9437852                    /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.5
7fa17e7be000-7fa17e7bf000 rw-p 0004e000 08:12 9437852                    /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2.10.5
7fa17e7bf000-7fa17e7c1000 rw-p 00000000 00:00 0 
7fa17e7c1000-7fa17e7ce000 r-xp 00000000 08:12 9441646                    /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.5
7fa17e7ce000-7fa17e9ce000 ---p 0000d000 08:12 9441646                    /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.5
7fa17e9ce000-7fa17e9cf000 r--p 0000d000 08:12 9441646                    /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.5
7fa17e9cf000-7fa17e9d0000 rw-p 0000e000 08:12 9441646                    /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2.10.5
7fa17e9d0000-7fa17ea17000 r-xp 00000000 08:12 9442831                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7fa17ea17000-7fa17ec16000 ---p 00047000 08:12 9442831                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7fa17ec16000-7fa17ec18000 r--p 00046000 08:12 9442831                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7fa17ec18000-7fa17ec1a000 rw-p 00048000 08:12 9442831                    /usr/lib/x86_64-linux-gnu/libgssapi_krb5.so.2.2
7fa17ec1a000-7fa17ec78000 r-xp 00000000 08:12 8913197                    /lib/x86_64-linux-gnu/libssl.so.1.0.0
7fa17ec78000-7fa17ee78000 ---p 0005e000 08:12 8913197                    /lib/x86_64-linux-gnu/libssl.so.1.0.0
7fa17ee78000-7fa17ee7c000 r--p 0005e000 08:12 8913197                    /lib/x86_64-linux-gnu/libssl.so.1.0.0
7fa17ee7c000-7fa17ee83000 rw-p 00062000 08:12 8913197                    /lib/x86_64-linux-gnu/libssl.so.1.0.0
7fa17ee83000-7fa17ee9e000 r-xp 00000000 08:12 9440880                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7fa17ee9e000-7fa17f09d000 ---p 0001b000 08:12 9440880                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7fa17f09d000-7fa17f09e000 r--p 0001a000 08:12 9440880                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7fa17f09e000-7fa17f09f000 rw-p 0001b000 08:12 9440880                    /usr/lib/x86_64-linux-gnu/librtmp.so.1
7fa17f09f000-7fa17f0d0000 r-xp 00000000 08:12 9438087                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7fa17f0d0000-7fa17f2d0000 ---p 00031000 08:12 9438087                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7fa17f2d0000-7fa17f2d1000 r--p 00031000 08:12 9438087                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7fa17f2d1000-7fa17f2d2000 rw-p 00032000 08:12 9438087                    /usr/lib/x86_64-linux-gnu/libidn.so.11.6.15
7fa17f2d2000-7fa17f492000 r-xp 00000000 08:12 8924891                    /lib/x86_64-linux-gnu/libc-2.23.so
7fa17f492000-7fa17f692000 ---p 001c0000 08:12 8924891                    /lib/x86_64-linux-gnu/libc-2.23.so
7fa17f692000-7fa17f696000 r--p 001c0000 08:12 8924891                    /lib/x86_64-linux-gnu/libc-2.23.so
7fa17f696000-7fa17f698000 rw-p 001c4000 08:12 8924891                    /lib/x86_64-linux-gnu/libc-2.23.so
7fa17f698000-7fa17f69c000 rw-p 00000000 00:00 0 
7fa17f69c000-7fa17f6b2000 r-xp 00000000 08:12 8917162                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fa17f6b2000-7fa17f8b1000 ---p 00016000 08:12 8917162                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fa17f8b1000-7fa17f8b2000 rw-p 00015000 08:12 8917162                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fa17f8b2000-7fa17f8d3000 r-xp 00000000 08:12 9438909                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fa17f8d3000-7fa17fad2000 ---p 00021000 08:12 9438909                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fa17fad2000-7fa17fad3000 r--p 00020000 08:12 9438909                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fa17fad3000-7fa17fad4000 rw-p 00021000 08:12 9438909                    /usr/lib/x86_64-linux-gnu/libgomp.so.1.0.0
7fa17fad4000-7fa17fbdc000 r-xp 00000000 08:12 8913131                    /lib/x86_64-linux-gnu/libm-2.23.so
7fa17fbdc000-7fa17fddb000 ---p 00108000 08:12 8913131                    /lib/x86_64-linux-gnu/libm-2.23.so
7fa17fddb000-7fa17fddc000 r--p 00107000 08:12 8913131                    /lib/x86_64-linux-gnu/libm-2.23.so
7fa17fddc000-7fa17fddd000 rw-p 00108000 08:12 8913131                    /lib/x86_64-linux-gnu/libm-2.23.so
7fa17fddd000-7fa17ff4f000 r-xp 00000000 08:12 9443671                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7fa17ff4f000-7fa18014f000 ---p 00172000 08:12 9443671                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7fa18014f000-7fa180159000 r--p 00172000 08:12 9443671                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7fa180159000-7fa18015b000 rw-p 0017c000 08:12 9443671                    /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.21
7fa18015b000-7fa18015f000 rw-p 00000000 00:00 0 
7fa18015f000-7fa1808a3000 r-xp 00000000 08:12 9438255                    /usr/lib/x86_64-linux-gnu/libcuda.so.378.09
7fa1808a3000-7fa180aa2000 ---p 00744000 08:12 9438255                    /usr/lib/x86_64-linux-gnu/libcuda.so.378.09
7fa180aa2000-7fa180bbf000 rw-p 00743000 08:12 9438255                    /usr/lib/x86_64-linux-gnu/libcuda.so.378.09
7fa180bbf000-7fa180bcd000 rw-p 00000000 00:00 0 
7fa180bcd000-7fa180bd0000 r-xp 00000000 08:12 8924893                    /lib/x86_64-linux-gnu/libdl-2.23.so
7fa180bd0000-7fa180dcf000 ---p 00003000 08:12 8924893                    /lib/x86_64-linux-gnu/libdl-2.23.so
7fa180dcf000-7fa180dd0000 r--p 00002000 08:12 8924893                    /lib/x86_64-linux-gnu/libdl-2.23.so
7fa180dd0000-7fa180dd1000 rw-p 00003000 08:12 8924893                    /lib/x86_64-linux-gnu/libdl-2.23.so
7fa180dd1000-7fa180feb000 r-xp 00000000 08:12 8913199                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7fa180feb000-7fa1811ea000 ---p 0021a000 08:12 8913199                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7fa1811ea000-7fa181206000 r--p 00219000 08:12 8913199                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7fa181206000-7fa181212000 rw-p 00235000 08:12 8913199                    /lib/x86_64-linux-gnu/libcrypto.so.1.0.0
7fa181212000-7fa181215000 rw-p 00000000 00:00 0 
7fa181215000-7fa181277000 r-xp 00000000 08:12 138211                     /usr/local/cuda-8.0/lib64/libcudart.so.8.0.61
7fa181277000-7fa181477000 ---p 00062000 08:12 138211                     /usr/local/cuda-8.0/lib64/libcudart.so.8.0.61
7fa181477000-7fa18147a000 rw-p 00062000 08:12 138211                     /usr/local/cuda-8.0/lib64/libcudart.so.8.0.61
7fa18147a000-7fa18147b000 rw-p 00000000 00:00 0 
7fa18147b000-7fa181493000 r-xp 00000000 08:12 8924890                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa181493000-7fa181692000 ---p 00018000 08:12 8924890                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa181692000-7fa181693000 r--p 00017000 08:12 8924890                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa181693000-7fa181694000 rw-p 00018000 08:12 8924890                    /lib/x86_64-linux-gnu/libpthread-2.23.so
7fa181694000-7fa181698000 rw-p 00000000 00:00 0 
7fa181698000-7fa1816a4000 r-xp 00000000 08:12 9440241                    /usr/lib/x86_64-linux-gnu/libjansson.so.4.7.0
7fa1816a4000-7fa1818a3000 ---p 0000c000 08:12 9440241                    /usr/lib/x86_64-linux-gnu/libjansson.so.4.7.0
7fa1818a3000-7fa1818a4000 r--p 0000b000 08:12 9440241                    /usr/lib/x86_64-linux-gnu/libjansson.so.4.7.0
7fa1818a4000-7fa1818a5000 rw-p 0000c000 08:12 9440241                    /usr/lib/x86_64-linux-gnu/libjansson.so.4.7.0
7fa1818a5000-7fa181910000 r-xp 00000000 08:12 9439280                    /usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0
7fa181910000-7fa181b10000 ---p 0006b000 08:12 9439280                    /usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0
7fa181b10000-7fa181b13000 r--p 0006b000 08:12 9439280                    /usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0
7fa181b13000-7fa181b14000 rw-p 0006e000 08:12 9439280                    /usr/lib/x86_64-linux-gnu/libcurl.so.4.4.0
7fa181b14000-7fa181b3a000 r-xp 00000000 08:12 8924889                    /lib/x86_64-linux-gnu/ld-2.23.so
7fa181cd3000-7fa181d15000 rw-p 00000000 00:00 0 
7fa181d17000-7fa181d39000 rw-p 00000000 00:00 0 
7fa181d39000-7fa181d3a000 r--p 00025000 08:12 8924889                    /lib/x86_64-linux-gnu/ld-2.23.so
7fa181d3a000-7fa181d3b000 rw-p 00026000 08:12 8924889                    /lib/x86_64-linux-gnu/ld-2.23.so
7fa181d3b000-7fa181d3c000 rw-p 00000000 00:00 0 
7ffc446e9000-7ffc4470b000 rw-p 00000000 00:00 0                          [stack]
7ffc4471a000-7ffc4471d000 r--p 00000000 00:00 0                          [vvar]
7ffc4471d000-7ffc4471f000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)
`

Any ideas about it? Seems some memory free issues in src? Or I need to use CUDA 6.5 instead?

**Comment by cauchyturing** [comment]
I use Ubuntu 16.04.

**Comment by quasars84** [comment]
Thanks for report - try git pull to latest version and see if fixed

**Comment by cauchyturing** [comment]
Cool, resolved, thanks!
